/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.ThietBi;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.border.MatteBorder;
import javax.swing.plaf.basic.BasicComboBoxUI;
import javax.swing.plaf.basic.BasicComboPopup;
import javax.swing.plaf.basic.ComboPopup;
import View.ThietBi.CustomTableRender;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Admin
 */
public class DeviceView extends javax.swing.JPanel {

    //	FORMAT
    private Font sgUI15 = new Font("Segoe UI", Font.BOLD, 15);
    private Font sgUI15p = new Font("Segoe UI", Font.PLAIN, 15);
    private Font sgUI15I = new Font("Segoe UI", Font.ITALIC, 15);
    private Font sgUI13 = new Font("Segoe UI", Font.PLAIN, 13);
    private Font sgUI13I = new Font("Segoe UI", Font.ITALIC, 13);
    private Font sgUI13b = new Font("Segoe UI", Font.BOLD, 13);
    private Font sgUI18b = new Font("Segoe UI", Font.BOLD, 17);
    private Font tNR13 = new Font("Times New Roman", Font.ITALIC, 13);
    private Font fontTittle = new Font("Tahoma", Font.BOLD, 25);
    private Font fontSubTittle = new Font("Tahoma", Font.BOLD, 20);
    private Font fontTable = new Font("Segoe UI", Font.BOLD, 13);
    private DecimalFormat dcf = new DecimalFormat("###,###");
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private Color btnoldColor = new Color(52, 152, 219);
    private Color texfieldColor = new Color(45, 52, 54);
    private String colorTableCode = "#dee9fc";
    private Font buttonFont = new Font("Segoe UI", Font.BOLD, 15);
    MatteBorder matteBorderCB = new MatteBorder(2, 2, 2, 2, Color.decode("#EFEFEF"));
    LineBorder lineCB = new LineBorder(Color.white);
    MatteBorder matteBorderCBDark = new MatteBorder(2, 2, 2, 2, Color.decode("#919191"));
    MatteBorder borderTxt = new MatteBorder(2, 2, 2, 2, Color.decode("#EFEFEF"));
    MatteBorder borderTxtDark = new MatteBorder(2, 2, 2, 2, Color.decode("#919191"));
    EmptyBorder emptyBorderTxt = new EmptyBorder(0, 7, 0, 7);
    EmptyBorder emptyBorderCB = new EmptyBorder(0, 7, 0, 0);
    
        
    public DeviceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDialogThemSua = new javax.swing.JDialog();
        jpnDialogHeader = new javax.swing.JPanel();
        jlbDialogHeader = new javax.swing.JLabel();
        jpnDialogContent = new javax.swing.JPanel();
        jlbDialogID = new javax.swing.JLabel();
        jtfDialogID = new javax.swing.JTextField();
        jlbDialogTen = new javax.swing.JLabel();
        jtfDialogTen = new javax.swing.JTextField();
        jlbDialogMoTa = new javax.swing.JLabel();
        jtfDialogMoTa = new javax.swing.JTextField();
        jpnDialogFooter = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jpnHeader = new javax.swing.JPanel();
        jlbHeader = new javax.swing.JLabel();
        jpnTopContent = new javax.swing.JPanel();
        jlbTimKiem = new javax.swing.JLabel();
        jtfTimKiem = new javax.swing.JTextField();
        jcbTimKiem = new javax.swing.JComboBox<>();
        jpnContent = new javax.swing.JPanel();
        jScrollTable = new javax.swing.JScrollPane();
        jTableThietBi = new javax.swing.JTable();
        jpnFooter = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXoaNhieu = new javax.swing.JButton();
        btnNhapExcel = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jDialogThemSua.setMinimumSize(new java.awt.Dimension(500, 300));
        jDialogThemSua.setPreferredSize(new java.awt.Dimension(500, 300));
        jDialogThemSua.getContentPane().setLayout(new javax.swing.BoxLayout(jDialogThemSua.getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jpnDialogHeader.setBackground(new java.awt.Color(102, 204, 255));
        jpnDialogHeader.setLayout(new java.awt.BorderLayout());

        jlbDialogHeader.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlbDialogHeader.setText("Thông tin thiết bị");
        jlbDialogHeader.setPreferredSize(new java.awt.Dimension(500, 50));
        jlbDialogHeader.setHorizontalAlignment(JLabel.CENTER);
        jpnDialogHeader.add(jlbDialogHeader, java.awt.BorderLayout.CENTER);

        jDialogThemSua.getContentPane().add(jpnDialogHeader);

        jpnDialogContent.setBackground(new java.awt.Color(255, 255, 255));
        jpnDialogContent.setPreferredSize(new java.awt.Dimension(500, 200));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 30, 0};
        jPanel3Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jpnDialogContent.setLayout(jPanel3Layout);

        jlbDialogID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbDialogID.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jpnDialogContent.add(jlbDialogID, gridBagConstraints);

        jtfDialogID.setEnabled(false);
        jtfDialogID.setPreferredSize(new java.awt.Dimension(200, 30));
        jtfDialogID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDialogIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jpnDialogContent.add(jtfDialogID, gridBagConstraints);

        jlbDialogTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbDialogTen.setText("Tên thiết bị");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jpnDialogContent.add(jlbDialogTen, gridBagConstraints);

        jtfDialogTen.setPreferredSize(new java.awt.Dimension(200, 30));
        jtfDialogTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDialogTenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jpnDialogContent.add(jtfDialogTen, gridBagConstraints);

        jlbDialogMoTa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbDialogMoTa.setText("Mô tả thiết bị");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jpnDialogContent.add(jlbDialogMoTa, gridBagConstraints);

        jtfDialogMoTa.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jpnDialogContent.add(jtfDialogMoTa, gridBagConstraints);

        jDialogThemSua.getContentPane().add(jpnDialogContent);

        jpnDialogFooter.setBackground(new java.awt.Color(255, 255, 255));
        jpnDialogFooter.setPreferredSize(new java.awt.Dimension(500, 60));

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setFont(buttonFont);
        btnXacNhan.setBackground(Color.decode("#ebf2fc"));
        btnXacNhan.setBorder(new EmptyBorder(8, 12, 8, 12));
        btnXacNhan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jpnDialogFooter.add(btnXacNhan);

        btnHuy.setText("Hủy");
        btnHuy.setFont(buttonFont);
        btnHuy.setBackground(Color.decode("#ebf2fc"));
        btnHuy.setBorder(new EmptyBorder(8, 12, 8, 12));
        btnHuy.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jpnDialogFooter.add(btnHuy);

        jDialogThemSua.getContentPane().add(jpnDialogFooter);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jpnHeader.setBackground(new java.awt.Color(153, 204, 255));
        jpnHeader.setPreferredSize(new java.awt.Dimension(993, 50));
        jpnHeader.setLayout(new java.awt.BorderLayout());

        jlbHeader.setBackground(new java.awt.Color(153, 204, 255));
        jlbHeader.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jlbHeader.setText("Quản lý thiết bị");
        jlbHeader.setToolTipText("");
        jlbHeader.setPreferredSize(new java.awt.Dimension(37, 30));
        jlbHeader.setHorizontalAlignment(JLabel.CENTER);
        jpnHeader.add(jlbHeader, java.awt.BorderLayout.CENTER);

        add(jpnHeader);

        jpnTopContent.setBackground(new java.awt.Color(255, 255, 255));
        jpnTopContent.setPreferredSize(new java.awt.Dimension(993, 60));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15);
        flowLayout1.setAlignOnBaseline(true);
        jpnTopContent.setLayout(flowLayout1);

        jlbTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTimKiem.setText("Tìm kiếm");
        jpnTopContent.add(jlbTimKiem);

        jtfTimKiem.setPreferredSize(new java.awt.Dimension(200, 30));
        jpnTopContent.add(jtfTimKiem);

        jcbTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "ID", "Tên thiết bị", "Mô tả thiết bị" }));
        jcbTimKiem.setPreferredSize(new java.awt.Dimension(200, 30));
        jcbTimKiem.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jcbTimKiem.setBackground(Color.WHITE);
        jcbTimKiem.setBorder(new MatteBorder(2, 2, 2, 0, Color.decode("#EFEFEF")));
        jcbTimKiem.setBackground(Color.white);
        jcbTimKiem.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        jcbTimKiem.setUI(new BasicComboBoxUI() {
            @Override
            protected ComboPopup createPopup() {
                BasicComboPopup basicComboPopup = new BasicComboPopup(comboBox);
                basicComboPopup.setBorder(new LineBorder(Color.white));
                return basicComboPopup;
            }
        });
        jpnTopContent.add(jcbTimKiem);

        add(jpnTopContent);

        jpnContent.setBackground(new java.awt.Color(255, 255, 255));
        jpnContent.setPreferredSize(new java.awt.Dimension(993, 600));
        jpnContent.setLayout(new java.awt.BorderLayout());

        jTableThietBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {1, 2, 3},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tên thiết bị", "Mô tả thiết bị"
            }
        ));
        jTableThietBi.setShowGrid(false);
        TableCellRenderer renderer = new CustomTableRender();
        for (int i = 0; i < jTableThietBi.getColumnCount(); i++) {
            jTableThietBi.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

        jTableThietBi.setBackground(Color.WHITE);
        jTableThietBi.setBorder(null);
        jTableThietBi.setRowHeight(35);
        jTableThietBi.setFont(new Font("Segoe UI", Font.BOLD, 13)); // Thiết lập font cho các dòng trong bảng
        jTableThietBi.setShowGrid(false);
        jTableThietBi.setRowHeight(35);

        jTableThietBi.getTableHeader().setPreferredSize(new Dimension(1, 30));
        jTableThietBi.getTableHeader().setFont(fontTable);
        Font headerFont = new Font("Segoe UI", Font.BOLD, 15);
        jTableThietBi.getTableHeader().setFont(headerFont);
        jTableThietBi.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableThietBi.getTableHeader().setBackground(Color.decode(colorTableCode));

        jTableThietBi.getColumnModel().getColumn(0).setPreferredWidth(50);
        jScrollTable.setViewportView(jTableThietBi);

        jScrollTable.getViewport().setBackground(Color.WHITE);

        jpnContent.add(jScrollTable, java.awt.BorderLayout.CENTER);

        add(jpnContent);

        jpnFooter.setBackground(new java.awt.Color(255, 255, 255));
        jpnFooter.setPreferredSize(new java.awt.Dimension(993, 60));
        jpnFooter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 15));

        btnThem.setText("Thêm");
        btnThem.setFont(buttonFont);
        btnThem.setBackground(Color.decode("#ebf2fc"));
        btnThem.setBorder(new EmptyBorder(8, 12, 8, 12));
        btnThem.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jpnFooter.add(btnThem);

        btnSua.setText("Sửa");
        btnSua.setFont(buttonFont);
        btnSua.setBackground(Color.decode("#ebf2fc"));
        btnSua.setBorder(new EmptyBorder(8, 12, 8, 12));
        btnSua.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jpnFooter.add(btnSua);

        btnXoa.setText("Xóa");
        btnXoa.setFont(buttonFont);
        btnXoa.setBackground(Color.decode("#ebf2fc"));
        btnXoa.setBorder(new EmptyBorder(8, 12, 8, 12));
        btnXoa.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jpnFooter.add(btnXoa);

        btnXoaNhieu.setText("Xóa nhiều");
        btnXoaNhieu.setFont(buttonFont);
        btnXoaNhieu.setBackground(Color.decode("#ebf2fc"));
        btnXoaNhieu.setBorder(new EmptyBorder(8, 12, 8, 12));
        btnXoaNhieu.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnXoaNhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhieuActionPerformed(evt);
            }
        });
        jpnFooter.add(btnXoaNhieu);

        btnNhapExcel.setText("Nhập file Excel");
        btnNhapExcel.setFont(buttonFont);
        btnNhapExcel.setBackground(Color.decode("#ebf2fc"));
        btnNhapExcel.setBorder(new EmptyBorder(8, 12, 8, 12));
        btnNhapExcel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnNhapExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapExcelActionPerformed(evt);
            }
        });
        jpnFooter.add(btnNhapExcel);

        btnRefresh.setText("Refresh");
        btnRefresh.setFont(buttonFont);
        btnRefresh.setBackground(Color.decode("#ebf2fc"));
        btnRefresh.setBorder(new EmptyBorder(8, 12, 8, 12));
        btnRefresh.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jpnFooter.add(btnRefresh);

        add(jpnFooter);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        btnXacNhan.setText("Xác nhận");
        jtfDialogID.setEnabled(false);
        
        jDialogThemSua.setLocationRelativeTo(null);
        jDialogThemSua.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhapExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhapExcelActionPerformed

    private void btnXoaNhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhieuActionPerformed
        // TODO add your handling code here:
        btnXacNhan.setText("Xóa");
        jtfDialogID.setEnabled(true);
        
        jDialogThemSua.setLocationRelativeTo(null);
        jDialogThemSua.setVisible(true);
        
    }//GEN-LAST:event_btnXoaNhieuActionPerformed

    private void jtfDialogTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDialogTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDialogTenActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        jDialogThemSua.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void jtfDialogIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDialogIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDialogIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnNhapExcel;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaNhieu;
    private javax.swing.JDialog jDialogThemSua;
    private javax.swing.JScrollPane jScrollTable;
    private javax.swing.JTable jTableThietBi;
    private javax.swing.JComboBox<String> jcbTimKiem;
    private javax.swing.JLabel jlbDialogHeader;
    private javax.swing.JLabel jlbDialogID;
    private javax.swing.JLabel jlbDialogMoTa;
    private javax.swing.JLabel jlbDialogTen;
    private javax.swing.JLabel jlbHeader;
    private javax.swing.JLabel jlbTimKiem;
    private javax.swing.JPanel jpnContent;
    private javax.swing.JPanel jpnDialogContent;
    private javax.swing.JPanel jpnDialogFooter;
    private javax.swing.JPanel jpnDialogHeader;
    private javax.swing.JPanel jpnFooter;
    private javax.swing.JPanel jpnHeader;
    private javax.swing.JPanel jpnTopContent;
    private javax.swing.JTextField jtfDialogID;
    private javax.swing.JTextField jtfDialogMoTa;
    private javax.swing.JTextField jtfDialogTen;
    private javax.swing.JTextField jtfTimKiem;
    // End of variables declaration//GEN-END:variables
}
